#!/bin/sh

ifconfig eth0 192.168.1.117

echo "********************"
echo "by LornYin 2017/4/24"
echo "********************"

mount -a
mkdir /dev/pts
mount -t devpts devpts /dev/pts
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s

